server:
  port: 9006
spring:
  application:
    name: my-admin-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
